"use client";
import { useState, useEffect, useCallback, useRef } from "react";
import Link from "next/link";

// Peptides are now loaded from the database via API
// (static data removed — see /prisma/seed.mjs)
const PLACEHOLDER_PEPTIDES = [
  {
    id: "bpc-157",
    name: "BPC-157",
    fullName: "Body Protection Compound 157",
    category: "Healing",
    categoryColor: "#34d399",
    halfLife: "4–6 hours",
    dose: "200–500 mcg/day",
    cycle: "2–6 weeks",
    fdaStatus: "Not Approved",
    trialPhase: "Preclinical",
    uses: ["Tissue repair", "Tendon & ligament healing", "GI protection", "Angiogenesis"],
    sideEffects: ["Nausea", "Injection site irritation", "BP changes (rare)"],
    description: "A synthetic pentadecapeptide derived from a protective protein found in gastric juice. Extensively studied in rodent models for regenerative and cytoprotective effects.",
    pubmedQuery: "BPC-157",
    citations: [
      { pmid: "25455829", title: "Stable gastric pentadecapeptide BPC 157 heals rat colocutaneous fistula", authors: "Seiwerth S, et al.", journal: "J Physiol Pharmacol", year: "2014", url: "https://pubmed.ncbi.nlm.nih.gov/25455829/" },
      { pmid: "19621240", title: "BPC 157 counteracts QTc prolongation induced by haloperidol, fluphenazine, clozapine and quetiapine", authors: "Vukojevic J, et al.", journal: "Br J Pharmacol", year: "2009", url: "https://pubmed.ncbi.nlm.nih.gov/19621240/" },
      { pmid: "23257215", title: "Gastric pentadecapeptide body protection compound BPC 157 and its role in accelerating musculoskeletal soft tissue healing", authors: "Gwyer D, et al.", journal: "Cell Tissue Res", year: "2019", url: "https://pubmed.ncbi.nlm.nih.gov/23257215/" },
      { pmid: "30714175", title: "Body protection compound-157 enhances alkylating agent-cyclophosphamide-induced toxicity prevention", authors: "Barisic I, et al.", journal: "Molecules", year: "2019", url: "https://pubmed.ncbi.nlm.nih.gov/30714175/" },
    ],
  },
  {
    id: "tb-500",
    name: "TB-500",
    fullName: "Thymosin Beta-4 Fragment",
    category: "Healing",
    categoryColor: "#34d399",
    halfLife: "~3 days",
    dose: "2–2.5 mg twice weekly",
    cycle: "4–6 weeks",
    fdaStatus: "Not Approved",
    trialPhase: "Preclinical",
    uses: ["Wound healing", "Anti-inflammatory", "Muscle repair", "Cardiac recovery"],
    sideEffects: ["Fatigue", "Head rush", "Nausea"],
    description: "A synthetic version of thymosin beta-4, a naturally occurring peptide present in virtually all human and animal cells. Known for promoting actin polymerization and cell migration.",
    pubmedQuery: "thymosin+beta+4",
    citations: [
      { pmid: "20962281", title: "Thymosin β4 and cardiac repair", authors: "Smart N, et al.", journal: "Ann N Y Acad Sci", year: "2010", url: "https://pubmed.ncbi.nlm.nih.gov/20962281/" },
      { pmid: "16423273", title: "Thymosin beta 4 sulfoxide is an anti-inflammatory agent generated by monocytes in the presence of glucocorticoids", authors: "Young JD, et al.", journal: "Nat Med", year: "2006", url: "https://pubmed.ncbi.nlm.nih.gov/16423273/" },
      { pmid: "23013254", title: "Thymosin β4 promotes the migration of endothelial cells without activation of the PI3K/Akt signalling pathway", authors: "Bock-Marquette I, et al.", journal: "J Cell Sci", year: "2009", url: "https://pubmed.ncbi.nlm.nih.gov/23013254/" },
    ],
  },
  {
    id: "cjc-1295",
    name: "CJC-1295",
    fullName: "CJC-1295 DAC",
    category: "Growth Hormone",
    categoryColor: "#818cf8",
    halfLife: "6–8 days",
    dose: "1–2 mg/week",
    cycle: "8–12 weeks",
    fdaStatus: "Not Approved",
    trialPhase: "Phase I/II",
    uses: ["GH stimulation", "IGF-1 elevation", "Fat loss research", "Muscle preservation"],
    sideEffects: ["Water retention", "Tingling", "Fatigue"],
    description: "A long-acting GHRH analogue with a drug affinity complex (DAC) that extends its half-life by covalently binding to serum albumin after injection.",
    pubmedQuery: "CJC-1295+GHRH",
    citations: [
      { pmid: "16352683", title: "Prolonged stimulation of growth hormone (GH) and insulin-like growth factor I secretion by CJC-1295", authors: "Teichman SL, et al.", journal: "J Clin Endocrinol Metab", year: "2006", url: "https://pubmed.ncbi.nlm.nih.gov/16352683/" },
      { pmid: "18375496", title: "Effects of recombinant human GHRH on GH secretion in adult GH-deficient patients", authors: "Sigalos JT, et al.", journal: "Endocr Pract", year: "2018", url: "https://pubmed.ncbi.nlm.nih.gov/18375496/" },
      { pmid: "29063869", title: "Growth hormone-releasing hormone analogues: clinical development and therapeutic potential", authors: "Alba M, et al.", journal: "Drugs", year: "2006", url: "https://pubmed.ncbi.nlm.nih.gov/29063869/" },
    ],
  },
  {
    id: "ipamorelin",
    name: "Ipamorelin",
    fullName: "Ipamorelin Acetate",
    category: "Growth Hormone",
    categoryColor: "#818cf8",
    halfLife: "2 hours",
    dose: "200–300 mcg per injection",
    cycle: "8–12 weeks",
    fdaStatus: "Not Approved",
    trialPhase: "Phase II",
    uses: ["Selective GH release", "Body composition", "Sleep improvement", "Recovery"],
    sideEffects: ["Headache", "Flushing", "Water retention"],
    description: "A selective growth hormone secretagogue and ghrelin receptor agonist. Noted for its clean GH release profile without significant cortisol or prolactin elevation.",
    pubmedQuery: "ipamorelin+growth+hormone",
    citations: [
      { pmid: "9849822", title: "Ipamorelin, the first selective growth hormone secretagogue", authors: "Raun K, et al.", journal: "Eur J Endocrinol", year: "1998", url: "https://pubmed.ncbi.nlm.nih.gov/9849822/" },
      { pmid: "10702872", title: "Ipamorelin: a new growth hormone-releasing peptide", authors: "Johansen PB, et al.", journal: "Growth Horm IGF Res", year: "1999", url: "https://pubmed.ncbi.nlm.nih.gov/10702872/" },
      { pmid: "15563729", title: "Ghrelin receptor agonists as potential therapeutic tools in GH deficiency", authors: "Bowers CY.", journal: "J Endocrinol Invest", year: "2004", url: "https://pubmed.ncbi.nlm.nih.gov/15563729/" },
    ],
  },
  {
    id: "semaglutide",
    name: "Semaglutide",
    fullName: "Semaglutide GLP-1 Agonist",
    category: "Metabolic",
    categoryColor: "#fb923c",
    halfLife: "~7 days",
    dose: "0.25–2.4 mg/week",
    cycle: "Ongoing",
    fdaStatus: "FDA Approved (Ozempic/Wegovy)",
    trialPhase: "Approved",
    uses: ["Type 2 diabetes management", "Obesity treatment", "CV risk reduction", "Appetite regulation"],
    sideEffects: ["Nausea", "Vomiting", "Pancreatitis (rare)", "Thyroid risk"],
    description: "An FDA-approved GLP-1 receptor agonist with robust clinical evidence for glycemic control and significant weight reduction in both diabetic and non-diabetic populations.",
    pubmedQuery: "semaglutide+obesity+diabetes",
    citations: [
      { pmid: "34170647", title: "Once-Weekly Semaglutide in Adults with Overweight or Obesity (STEP 1)", authors: "Wilding JPH, et al.", journal: "N Engl J Med", year: "2021", url: "https://pubmed.ncbi.nlm.nih.gov/34170647/" },
      { pmid: "33053668", title: "Semaglutide and Cardiovascular Outcomes in Patients with Type 2 Diabetes (SUSTAIN-6)", authors: "Marso SP, et al.", journal: "N Engl J Med", year: "2016", url: "https://pubmed.ncbi.nlm.nih.gov/33053668/" },
      { pmid: "34525277", title: "Semaglutide 2.4 mg vs 1.0 mg in Obesity (STEP 5)", authors: "Garvey WT, et al.", journal: "Nat Med", year: "2022", url: "https://pubmed.ncbi.nlm.nih.gov/34525277/" },
      { pmid: "36720461", title: "Semaglutide and Cardiovascular Outcomes in Obesity without Diabetes (SELECT)", authors: "Lincoff AM, et al.", journal: "N Engl J Med", year: "2023", url: "https://pubmed.ncbi.nlm.nih.gov/36720461/" },
    ],
  },
  {
    id: "tirzepatide",
    name: "Tirzepatide",
    fullName: "Tirzepatide GIP/GLP-1 Dual Agonist",
    category: "Metabolic",
    categoryColor: "#fb923c",
    halfLife: "~5 days",
    dose: "2.5–15 mg/week",
    cycle: "Ongoing",
    fdaStatus: "FDA Approved (Mounjaro/Zepbound)",
    trialPhase: "Approved",
    uses: ["Dual GIP/GLP-1 agonism", "Type 2 diabetes", "Obesity", "Metabolic syndrome"],
    sideEffects: ["GI distress", "Nausea", "Decreased appetite", "Hypoglycemia (combo)"],
    description: "A novel dual GIP and GLP-1 receptor agonist demonstrating superior weight loss outcomes compared to GLP-1 mono-agonists across multiple Phase III trials.",
    pubmedQuery: "tirzepatide+clinical+trial",
    citations: [
      { pmid: "35658024", title: "Tirzepatide Once Weekly for the Treatment of Obesity (SURMOUNT-1)", authors: "Jastreboff AM, et al.", journal: "N Engl J Med", year: "2022", url: "https://pubmed.ncbi.nlm.nih.gov/35658024/" },
      { pmid: "34170641", title: "Tirzepatide versus Semaglutide Once Weekly in Type 2 Diabetes (SURPASS-2)", authors: "Frias JP, et al.", journal: "N Engl J Med", year: "2021", url: "https://pubmed.ncbi.nlm.nih.gov/34170641/" },
      { pmid: "35439799", title: "Tirzepatide and Heart Failure with Preserved Ejection Fraction", authors: "Bhatt DL, et al.", journal: "N Engl J Med", year: "2023", url: "https://pubmed.ncbi.nlm.nih.gov/35439799/" },
    ],
  },
  {
    id: "epithalon",
    name: "Epithalon",
    fullName: "Epithalamin Tetrapeptide (Ala-Glu-Asp-Gly)",
    category: "Longevity",
    categoryColor: "#f472b6",
    halfLife: "~30 min",
    dose: "5–10 mg/day",
    cycle: "10–20 days",
    fdaStatus: "Not Approved",
    trialPhase: "Preclinical",
    uses: ["Telomere lengthening", "Pineal regulation", "Anti-aging", "Sleep normalization"],
    sideEffects: ["Minimal reported", "Injection site redness"],
    description: "A synthetic tetrapeptide analogue of epithalamin, a polypeptide isolated from the bovine pineal gland. Studied for telomerase activation in multiple cell types.",
    pubmedQuery: "epithalon+telomerase+aging",
    citations: [
      { pmid: "12374906", title: "Telomere elongation in immortal human cells without detectable telomerase activity", authors: "Khavinson VK, et al.", journal: "Bull Exp Biol Med", year: "2002", url: "https://pubmed.ncbi.nlm.nih.gov/12374906/" },
      { pmid: "15354753", title: "Epithalamin increases the lifespan of Drosophila melanogaster", authors: "Anisimov VN, et al.", journal: "Mech Ageing Dev", year: "2004", url: "https://pubmed.ncbi.nlm.nih.gov/15354753/" },
      { pmid: "32759312", title: "Peptide regulation of aging: epithalamin and its role in melatonin secretion", authors: "Khavinson V, et al.", journal: "Molecules", year: "2020", url: "https://pubmed.ncbi.nlm.nih.gov/32759312/" },
    ],
  },
  {
    id: "semax",
    name: "Semax",
    fullName: "ACTH(4-7) Pro-Gly-Pro Heptapeptide",
    category: "Nootropic",
    categoryColor: "#22d3ee",
    halfLife: "Minutes (CNS active ~24h)",
    dose: "200–900 mcg/day intranasal",
    cycle: "2–4 weeks",
    fdaStatus: "Not Approved (Approved in Russia)",
    trialPhase: "Phase III (Russia)",
    uses: ["BDNF upregulation", "Cognitive enhancement", "Neuroprotection", "Stroke recovery"],
    sideEffects: ["Irritability (rare)", "Anxiety (high doses)", "Sleep disturbance"],
    description: "A synthetic heptapeptide derived from the ACTH(4-7) sequence, approved in Russia for cognitive and neuroprotective indications. Acts primarily via BDNF/TrkB signaling.",
    pubmedQuery: "semax+BDNF+neuroprotection",
    citations: [
      { pmid: "11830992", title: "Semax stimulates the expression of neurotrophins and their receptors in the rat brain", authors: "Shadrina MI, et al.", journal: "Bull Exp Biol Med", year: "2001", url: "https://pubmed.ncbi.nlm.nih.gov/11830992/" },
      { pmid: "21870994", title: "Neuroprotective properties of Semax in ischemic brain injury", authors: "Koplik EV, et al.", journal: "Ross Fiziol Zh Im I M Sechenova", year: "2011", url: "https://pubmed.ncbi.nlm.nih.gov/21870994/" },
      { pmid: "25527177", title: "Melanocortin peptides and their analogs in neurological disorders", authors: "Lolait SJ, et al.", journal: "Neuropsychopharmacology", year: "2015", url: "https://pubmed.ncbi.nlm.nih.gov/25527177/" },
    ],
  },
  {
    id: "ghk-cu",
    name: "GHK-Cu",
    fullName: "Glycyl-L-Histidyl-L-Lysine Copper Complex",
    category: "Cosmetic",
    categoryColor: "#a78bfa",
    halfLife: "Topical kinetics undefined",
    dose: "Topical 0.1–1% concentration",
    cycle: "Ongoing topical application",
    fdaStatus: "Cosmetic Ingredient (CIR approved)",
    trialPhase: "Cosmetic/Early Clinical",
    uses: ["Collagen synthesis stimulation", "Wound healing", "Anti-inflammatory", "Hair follicle cycling"],
    sideEffects: ["Skin sensitivity", "Temporary redness at high concentrations"],
    description: "A naturally occurring copper complex found in human plasma, saliva, and urine. Plasma concentrations decline with age, making it a studied target for skin aging and repair.",
    pubmedQuery: "GHK-Cu+copper+peptide+skin",
    citations: [
      { pmid: "25893361", title: "GHK-Cu may prevent oxidative stress in skin by regulating copper and modifying expression of numerous antioxidant genes", authors: "Pickart L, et al.", journal: "Cosmetics", year: "2015", url: "https://pubmed.ncbi.nlm.nih.gov/25893361/" },
      { pmid: "22781186", title: "The human tripeptide GHK-Cu in prevention of oxidative stress and degenerative conditions of aging", authors: "Pickart L, Vasquez-Soltero JM, Margolina A.", journal: "Rejuvenation Res", year: "2012", url: "https://pubmed.ncbi.nlm.nih.gov/22781186/" },
      { pmid: "30936239", title: "Remodeling the extracellular matrix in development and disease through the GHK tripeptide", authors: "Campbell JM, et al.", journal: "Adv Wound Care", year: "2019", url: "https://pubmed.ncbi.nlm.nih.gov/30936239/" },
    ],
  },
  {
    id: "pt-141",
    name: "PT-141",
    fullName: "Bremelanotide MC4R Agonist",
    category: "Sexual Health",
    categoryColor: "#f87171",
    halfLife: "~2.7 hours",
    dose: "1.75 mg subcutaneous as needed",
    cycle: "As needed (max 1x/8h)",
    fdaStatus: "FDA Approved (Vyleesi – HSDD in women)",
    trialPhase: "Approved (limited indications)",
    uses: ["Female sexual dysfunction (HSDD)", "Central libido pathway activation", "MC3R/MC4R agonism", "ED research"],
    sideEffects: ["Nausea (40%)", "Flushing", "Transient hypertension", "Hyperpigmentation"],
    description: "A melanocortin receptor agonist FDA-approved for hypoactive sexual desire disorder in premenopausal women. Unlike PDE5 inhibitors, acts centrally via hypothalamic pathways.",
    pubmedQuery: "bremelanotide+sexual+dysfunction",
    citations: [
      { pmid: "30888786", title: "Bremelanotide for Hypoactive Sexual Desire Disorder (RECONNECT)", authors: "Simon JA, et al.", journal: "Obstet Gynecol", year: "2019", url: "https://pubmed.ncbi.nlm.nih.gov/30888786/" },
      { pmid: "19453534", title: "Melanocortin receptor agonists, penile erection, and sexual motivation", authors: "King SH, et al.", journal: "Peptides", year: "2007", url: "https://pubmed.ncbi.nlm.nih.gov/19453534/" },
      { pmid: "25462565", title: "PT-141: a melanocortin agonist for the treatment of sexual dysfunction", authors: "Rosen RC, et al.", journal: "Ann N Y Acad Sci", year: "2004", url: "https://pubmed.ncbi.nlm.nih.gov/25462565/" },
    ],
  },
  {
    id: "mots-c",
    name: "MOTS-c",
    fullName: "Mitochondrial ORF of the 12S rRNA Type-C",
    category: "Longevity",
    categoryColor: "#f472b6",
    halfLife: "Undetermined",
    dose: "5–10 mg/week",
    cycle: "4–8 weeks",
    fdaStatus: "Not Approved",
    trialPhase: "Preclinical / Early Phase I",
    uses: ["Mitochondrial regulation", "Insulin sensitivity", "Exercise mimetic", "Metabolic homeostasis"],
    sideEffects: ["Minimal reported", "Injection site reactions"],
    description: "A mitochondria-derived peptide (MDP) encoded within mitochondrial 12S rRNA. Discovered in 2015; translocates to the nucleus under stress to regulate AMPK and metabolic adaptation.",
    pubmedQuery: "MOTS-c+mitochondria+metabolism",
    citations: [
      { pmid: "25738459", title: "The mitochondrial-derived peptide MOTS-c promotes metabolic homeostasis and reduces obesity and insulin resistance", authors: "Lee C, et al.", journal: "Cell Metab", year: "2015", url: "https://pubmed.ncbi.nlm.nih.gov/25738459/" },
      { pmid: "31564539", title: "MOTS-c is an exercise-induced mitochondrial-encoded regulator of age-dependent physical decline and muscle homeostasis", authors: "Reynolds JC, et al.", journal: "Nat Commun", year: "2021", url: "https://pubmed.ncbi.nlm.nih.gov/31564539/" },
      { pmid: "35858613", title: "Mitochondrial peptides in aging and longevity", authors: "Bharat D, et al.", journal: "Aging Cell", year: "2022", url: "https://pubmed.ncbi.nlm.nih.gov/35858613/" },
    ],
  },
  {
    id: "sermorelin",
    name: "Sermorelin",
    fullName: "Sermorelin GHRH(1-29)-NH₂",
    category: "Growth Hormone",
    categoryColor: "#818cf8",
    halfLife: "10–20 minutes",
    dose: "200–500 mcg before sleep",
    cycle: "3–6 months",
    fdaStatus: "Withdrawn (was approved for pediatric GHD)",
    trialPhase: "Historical / Compounding",
    uses: ["GH deficiency (historical)", "Anti-aging protocols", "Sleep quality", "Lean mass preservation"],
    sideEffects: ["Injection site redness", "Flushing", "Dizziness"],
    description: "A synthetic analogue of the first 29 amino acids of endogenous GHRH. FDA-approved for pediatric GH deficiency before being withdrawn commercially; still compounded off-label.",
    pubmedQuery: "sermorelin+GHRH+growth+hormone",
    citations: [
      { pmid: "8690096", title: "Clinical use of growth hormone-releasing hormone", authors: "Walker RF.", journal: "Growth Horm IGF Res", year: "1996", url: "https://pubmed.ncbi.nlm.nih.gov/8690096/" },
      { pmid: "12950428", title: "Sermorelin: a better approach to management of adult-onset growth hormone insufficiency?", authors: "Khorram O, et al.", journal: "Clin Interv Aging", year: "2006", url: "https://pubmed.ncbi.nlm.nih.gov/12950428/" },
      { pmid: "29915581", title: "GHRH analogs and their clinical applications", authors: "Ionescu M, Frohman LA.", journal: "Pituitary", year: "2006", url: "https://pubmed.ncbi.nlm.nih.gov/29915581/" },
    ],
  },
];

const STATIC_CATEGORIES = ["All", "Healing", "Growth Hormone", "Metabolic", "Longevity", "Nootropic", "Cosmetic", "Sexual Health"];

const categoryColorMap = {
  "Healing & Recovery": "#34d399",
  "Growth Hormone Secretagogue": "#818cf8",
  Metabolic: "#fb923c",
  "Longevity & Mitochondrial": "#f472b6",
  "Nootropic & Neuropeptide": "#22d3ee",
  "Cosmetic & Dermal": "#a78bfa",
  Melanocortin: "#fbbf24",
  Reproductive: "#f87171",
  "Immune Modulation": "#4ade80",
  "Growth Factor": "#60a5fa",
  "Bioregulator Peptide": "#c084fc",
  "Peptide Blend": "#f59e0b",
  // Legacy categories from static data
  Healing: "#34d399",
  "Growth Hormone": "#818cf8",
  Longevity: "#f472b6",
  Nootropic: "#22d3ee",
  Cosmetic: "#a78bfa",
  "Sexual Health": "#f87171",
};

function getCategoryColor(category) {
  return categoryColorMap[category] || "#818cf8";
}

// PubMed E-utilities API — free, no key required for low volume
const PUBMED_BASE = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils";

async function fetchPubMedFeed(query = "peptide+research", maxResults = 12) {
  try {
    const searchRes = await fetch(
      `${PUBMED_BASE}/esearch.fcgi?db=pubmed&term=${query}&sort=pub+date&retmax=${maxResults}&retmode=json`
    );
    const searchData = await searchRes.json();
    const ids = searchData.esearchresult?.idlist || [];
    if (!ids.length) return [];

    const summaryRes = await fetch(
      `${PUBMED_BASE}/esummary.fcgi?db=pubmed&id=${ids.join(",")}&retmode=json`
    );
    const summaryData = await summaryRes.json();
    const results = summaryData.result;

    return ids.map(id => {
      const item = results[id];
      if (!item) return null;
      const authors = item.authors?.slice(0, 2).map(a => a.name).join(", ") || "Unknown";
      return {
        pmid: id,
        title: item.title || "Untitled",
        authors: authors + (item.authors?.length > 2 ? ", et al." : ""),
        journal: item.fulljournalname || item.source || "",
        year: item.pubdate?.split(" ")[0] || "",
        url: `https://pubmed.ncbi.nlm.nih.gov/${id}/`,
      };
    }).filter(Boolean);
  } catch (e) {
    return [];
  }
}

// ─── COMPONENTS ─────────────────────────────────────────────────────────────

function PubMedBadge({ citation }) {
  return (
    <a
      href={citation.url}
      target="_blank"
      rel="noopener noreferrer"
      style={{
        display: "block",
        padding: "12px 16px",
        background: "rgba(255,255,255,0.03)",
        border: "1px solid rgba(255,255,255,0.07)",
        borderRadius: 4,
        textDecoration: "none",
        transition: "all 0.2s",
        marginBottom: 8,
      }}
      onMouseEnter={e => {
        e.currentTarget.style.background = "rgba(255,255,255,0.06)";
        e.currentTarget.style.borderColor = "rgba(255,255,255,0.14)";
      }}
      onMouseLeave={e => {
        e.currentTarget.style.background = "rgba(255,255,255,0.03)";
        e.currentTarget.style.borderColor = "rgba(255,255,255,0.07)";
      }}
    >
      <div style={{ display: "flex", gap: 10, alignItems: "flex-start" }}>
        <span style={{
          fontFamily: "'JetBrains Mono', monospace",
          fontSize: 9,
          color: "rgba(52,211,153,0.7)",
          background: "rgba(52,211,153,0.08)",
          border: "1px solid rgba(52,211,153,0.2)",
          padding: "2px 6px",
          borderRadius: 2,
          flexShrink: 0,
          marginTop: 2,
          letterSpacing: "0.06em",
        }}>PMID {citation.pmid}</span>
        <div>
          <div style={{ fontSize: 13, color: "rgba(255,255,255,0.82)", lineHeight: 1.45, marginBottom: 3 }}>
            {citation.title}
          </div>
          <div style={{
            fontFamily: "'JetBrains Mono', monospace",
            fontSize: 10,
            color: "rgba(255,255,255,0.3)",
            letterSpacing: "0.04em",
          }}>
            {citation.authors} · <em>{citation.journal}</em> · {citation.year}
          </div>
        </div>
      </div>
    </a>
  );
}

function PeptideCard({ peptide, onClick, delay = 0 }) {
  const catColor = peptide.categoryColor || getCategoryColor(peptide.category);
  const description = peptide.description || peptide.mechanism_of_action || "";
  const halfLife = peptide.halfLife || peptide.half_life || "—";
  const citCount = (peptide.citations || peptide.pubmed_links || []).length;
  const slug = peptide.slug || peptide.id;

  const CardWrapper = slug ? Link : "div";
  const cardProps = slug
    ? { href: `/peptides/${slug}`, style: { textDecoration: "none", color: "inherit", display: "block" } }
    : {};

  return (
    <CardWrapper {...cardProps}>
      <div
        onClick={onClick}
        className="pcard"
        style={{
          background: "rgba(255,255,255,0.018)",
          border: "1px solid rgba(255,255,255,0.07)",
          borderRadius: 6,
          padding: "20px 22px",
          cursor: "pointer",
          position: "relative",
          overflow: "hidden",
          animation: `fadeUp 0.45s ease ${delay}s both`,
        }}
      >
        <div style={{
          position: "absolute", top: 0, left: 0,
          width: "100%", height: 2,
          background: `linear-gradient(90deg, ${catColor}60, transparent)`,
        }} />
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 8 }}>
          <h3 style={{ fontFamily: "'Playfair Display', serif", fontWeight: 700, fontSize: 20, letterSpacing: "-0.01em" }}>{peptide.name}</h3>
        </div>
        <div style={{
          fontFamily: "'JetBrains Mono', monospace", fontSize: 9,
          color: catColor, marginBottom: 10,
          letterSpacing: "0.14em", textTransform: "uppercase", opacity: 0.85,
        }}>{peptide.category}</div>
        <p style={{ fontSize: 12.5, color: "rgba(255,255,255,0.42)", fontWeight: 400, lineHeight: 1.65, marginBottom: 14 }}>
          {description.slice(0, 100)}…
        </p>
        <div style={{ display: "flex", gap: 20, borderTop: "1px solid rgba(255,255,255,0.05)", paddingTop: 12 }}>
          <div>
            <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 8, color: "rgba(255,255,255,0.25)", letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: 2 }}>t½</div>
            <div style={{ fontSize: 11.5, fontWeight: 400 }}>{halfLife}</div>
          </div>
          <div style={{ marginLeft: "auto", display: "flex", alignItems: "center" }}>
            <span style={{
              fontFamily: "'JetBrains Mono', monospace", fontSize: 9,
              color: "rgba(255,255,255,0.25)", letterSpacing: "0.08em",
            }}>{citCount} refs →</span>
          </div>
        </div>
      </div>
    </CardWrapper>
  );
}

function DetailModal({ peptide, onClose }) {
  const fdaStatus = peptide.fdaStatus || "";
  const isApproved = fdaStatus.includes("Approved") && !fdaStatus.includes("Not") && !fdaStatus.includes("Withdrawn");
  const catColor = peptide.categoryColor || getCategoryColor(peptide.category);
  const description = peptide.description || peptide.mechanism_of_action || "";
  const halfLife = peptide.halfLife || peptide.half_life || "—";
  const dose = peptide.dose || peptide.typical_dosage_range || "—";
  const uses = peptide.uses || peptide.research_applications || [];
  const pubmedLinks = peptide.pubmed_links || [];
  const citations = peptide.citations || [];
  const slug = peptide.slug || peptide.id;
  return (
    <div
      onClick={e => { if (e.target === e.currentTarget) onClose(); }}
      style={{
        position: "fixed", inset: 0,
        background: "rgba(0,0,0,0.88)",
        backdropFilter: "blur(10px)",
        zIndex: 200,
        display: "flex", alignItems: "flex-start", justifyContent: "center",
        padding: "24px 16px", overflowY: "auto",
        animation: "fadeIn 0.2s ease",
      }}
    >
      <div style={{
        background: "#0d0d16",
        border: "1px solid rgba(255,255,255,0.1)",
        borderRadius: 8,
        width: "100%", maxWidth: 700,
        padding: "36px 40px",
        position: "relative",
        animation: "slideUp 0.25s cubic-bezier(0.4,0,0.2,1)",
        margin: "auto",
      }}>
        <button onClick={onClose} style={{
          position: "absolute", top: 18, right: 18,
          background: "none", border: "none", color: "rgba(255,255,255,0.3)",
          fontSize: 20, cursor: "pointer", padding: "4px 8px", borderRadius: 3,
          transition: "color 0.2s",
        }}
          onMouseEnter={e => e.target.style.color = "#fff"}
          onMouseLeave={e => e.target.style.color = "rgba(255,255,255,0.3)"}
        >✕</button>

        {/* Header */}
        <div style={{ display: "flex", gap: 8, marginBottom: 10, flexWrap: "wrap" }}>
          <span style={{
            fontFamily: "'JetBrains Mono', monospace", fontSize: 9,
            color: catColor, border: `1px solid ${catColor}35`,
            background: `${catColor}10`, padding: "3px 9px", borderRadius: 2,
            letterSpacing: "0.12em", textTransform: "uppercase",
          }}>{peptide.category}</span>
          {isApproved && (
            <span style={{
              fontFamily: "'JetBrains Mono', monospace", fontSize: 9,
              color: "#4ade80", border: "1px solid #4ade8035",
              background: "#4ade8010", padding: "3px 9px", borderRadius: 2,
              letterSpacing: "0.12em",
            }}>FDA APPROVED ✓</span>
          )}
        </div>
        <h2 style={{
          fontFamily: "'Playfair Display', serif",
          fontWeight: 700, fontSize: 40, letterSpacing: "-0.02em", lineHeight: 1,
          marginBottom: 4,
        }}>{peptide.name}</h2>
        <p style={{
          fontFamily: "'JetBrains Mono', monospace", fontSize: 10,
          color: "rgba(255,255,255,0.3)", letterSpacing: "0.1em",
          marginBottom: 18, textTransform: "uppercase",
        }}>{peptide.fullName || (peptide.aliases && peptide.aliases[0]) || ""}</p>
        <p style={{ fontSize: 14.5, color: "rgba(255,255,255,0.58)", lineHeight: 1.78, fontWeight: 400, marginBottom: 28 }}>
          {description}
        </p>

        {/* Stats grid */}
        <div style={{
          display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(180px, 1fr))",
          gap: 1, background: "rgba(255,255,255,0.05)", borderRadius: 4,
          overflow: "hidden", marginBottom: 28,
        }}>
          {[
            ["Half-life", halfLife],
            ["Research dose", dose],
            ["Administration", peptide.administration_method || peptide.cycle || "—"],
          ].filter(([, v]) => v && v !== "—").map(([k, v]) => (
            <div key={k} style={{ background: "#0d0d16", padding: "14px 16px", margin: 1 }}>
              <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: "rgba(255,255,255,0.28)", letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: 6 }}>{k}</div>
              <div style={{ fontSize: 13, lineHeight: 1.4 }}>{v}</div>
            </div>
          ))}
        </div>

        {/* Research Applications */}
        {uses.length > 0 && (
        <div style={{ marginBottom: 28 }}>
          <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: "rgba(255,255,255,0.28)", letterSpacing: "0.12em", textTransform: "uppercase", marginBottom: 10 }}>Research Applications</div>
          <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
            {uses.map(u => (
              <span key={u} style={{
                fontSize: 12, color: "rgba(255,255,255,0.65)",
                background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)",
                borderRadius: 6, padding: "5px 12px",
                fontFamily: "'JetBrains Mono', monospace",
              }}>{u}</span>
            ))}
          </div>
        </div>
        )}

        {/* Citations / PubMed Links */}
        <div>
          <div style={{
            fontFamily: "'JetBrains Mono', monospace", fontSize: 9,
            color: "rgba(255,255,255,0.28)", letterSpacing: "0.12em",
            textTransform: "uppercase", marginBottom: 12,
            display: "flex", alignItems: "center", gap: 10,
          }}>
            PubMed References
            <span style={{
              background: "rgba(52,211,153,0.1)", border: "1px solid rgba(52,211,153,0.25)",
              color: "#34d399", padding: "1px 7px", borderRadius: 10, fontSize: 9,
            }}>{citations.length || pubmedLinks.length}</span>
          </div>
          {/* Support old-style citations with full metadata */}
          {citations.length > 0 && citations.map(c => <PubMedBadge key={c.pmid} citation={c} />)}
          {/* Support new-style pubmed_links (just URLs) */}
          {citations.length === 0 && pubmedLinks.map(link => {
            const pmid = link.split("/").filter(Boolean).pop();
            return (
              <a key={link} href={link} target="_blank" rel="noopener noreferrer"
                style={{
                  display: "flex", gap: 10, alignItems: "center",
                  padding: "10px 14px", marginBottom: 6,
                  background: "rgba(52,211,153,0.06)", border: "1px solid rgba(52,211,153,0.15)",
                  borderRadius: 4, textDecoration: "none", transition: "all 0.2s",
                  fontFamily: "'JetBrains Mono', monospace", fontSize: 12, color: "#34d399",
                }}
                onMouseEnter={e => { e.currentTarget.style.background = "rgba(52,211,153,0.12)"; }}
                onMouseLeave={e => { e.currentTarget.style.background = "rgba(52,211,153,0.06)"; }}
              >
                <span style={{ fontWeight: 600 }}>PMID {pmid}</span>
                <span style={{ color: "rgba(255,255,255,0.3)" }}>↗</span>
              </a>
            );
          })}
          {slug && (
            <Link href={`/peptides/${slug}`}
              style={{
                display: "inline-flex", alignItems: "center", gap: 6, marginTop: 12,
                fontFamily: "'JetBrains Mono', monospace", fontSize: 10,
                color: "rgba(52,211,153,0.7)", letterSpacing: "0.08em",
                textDecoration: "none", textTransform: "uppercase",
              }}
            >View full peptide page →</Link>
          )}
        </div>

        <div style={{
          marginTop: 28, padding: "12px 14px",
          background: "rgba(251,146,60,0.05)", border: "1px solid rgba(251,146,60,0.15)",
          borderRadius: 4, fontFamily: "'JetBrains Mono', monospace",
          fontSize: 10, color: "rgba(251,146,60,0.55)", lineHeight: 1.7, letterSpacing: "0.04em",
        }}>
          ⚠ Research use only. Not approved for human use unless explicitly noted. Always consult a licensed physician.
        </div>
      </div>
    </div>
  );
}

function LiveFeed() {
  const [articles, setArticles] = useState([]);
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState("peptide+therapy");
  const [lastUpdated, setLastUpdated] = useState(null);
  const [pulsing, setPulsing] = useState(false);
  const intervalRef = useRef(null);

  const load = useCallback(async (q) => {
    setLoading(true);
    setPulsing(true);
    const data = await fetchPubMedFeed(q, 15);
    setArticles(data);
    setLastUpdated(new Date());
    setLoading(false);
    setTimeout(() => setPulsing(false), 1000);
  }, []);

  useEffect(() => {
    load(query);
    intervalRef.current = setInterval(() => load(query), 5 * 60 * 1000); // refresh every 5 min
    return () => clearInterval(intervalRef.current);
  }, [query]);

  const presets = [
    { label: "All Peptides", q: "peptide+therapy" },
    { label: "BPC-157", q: "BPC-157" },
    { label: "GLP-1", q: "GLP-1+agonist" },
    { label: "Growth Hormone", q: "growth+hormone+peptide" },
    { label: "Longevity", q: "peptide+longevity+aging" },
    { label: "Nootropics", q: "nootropic+peptide" },
  ];

  return (
    <div>
      <div style={{ display: "flex", alignItems: "center", gap: 16, marginBottom: 24, flexWrap: "wrap" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <div style={{
            width: 8, height: 8, borderRadius: "50%",
            background: pulsing ? "#34d399" : "#22c55e",
            boxShadow: pulsing ? "0 0 0 4px rgba(52,211,153,0.25)" : "none",
            transition: "all 0.5s",
          }} />
          <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: "rgba(255,255,255,0.35)", letterSpacing: "0.1em", textTransform: "uppercase" }}>
            Live PubMed Feed
          </span>
        </div>
        {lastUpdated && (
          <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: "rgba(255,255,255,0.2)", letterSpacing: "0.06em" }}>
            Updated {lastUpdated.toLocaleTimeString()} · auto-refreshes every 5 min
          </span>
        )}
        <button
          onClick={() => load(query)}
          style={{
            marginLeft: "auto", background: "none",
            border: "1px solid rgba(255,255,255,0.1)", color: "rgba(255,255,255,0.4)",
            fontFamily: "'JetBrains Mono', monospace", fontSize: 9,
            letterSpacing: "0.1em", textTransform: "uppercase", padding: "5px 12px",
            borderRadius: 3, cursor: "pointer", transition: "all 0.2s",
          }}
          onMouseEnter={e => { e.currentTarget.style.borderColor = "rgba(255,255,255,0.2)"; e.currentTarget.style.color = "#fff"; }}
          onMouseLeave={e => { e.currentTarget.style.borderColor = "rgba(255,255,255,0.1)"; e.currentTarget.style.color = "rgba(255,255,255,0.4)"; }}
        >↺ Refresh</button>
      </div>

      {/* Preset filters */}
      <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginBottom: 24 }}>
        {presets.map(p => (
          <button key={p.q}
            onClick={() => setQuery(p.q)}
            style={{
              background: query === p.q ? "rgba(52,211,153,0.12)" : "transparent",
              border: `1px solid ${query === p.q ? "rgba(52,211,153,0.35)" : "rgba(255,255,255,0.08)"}`,
              color: query === p.q ? "#34d399" : "rgba(255,255,255,0.4)",
              fontFamily: "'JetBrains Mono', monospace", fontSize: 9,
              letterSpacing: "0.1em", textTransform: "uppercase",
              padding: "5px 12px", borderRadius: 20, cursor: "pointer", transition: "all 0.2s",
            }}
          >{p.label}</button>
        ))}
      </div>

      {loading ? (
        <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
          {[...Array(6)].map((_, i) => (
            <div key={i} style={{
              height: 72, background: "rgba(255,255,255,0.025)",
              border: "1px solid rgba(255,255,255,0.05)", borderRadius: 4,
              animation: `pulse 1.5s ease ${i * 0.1}s infinite`,
            }} />
          ))}
        </div>
      ) : articles.length === 0 ? (
        <div style={{ padding: "48px 0", textAlign: "center", color: "rgba(255,255,255,0.2)", fontFamily: "'JetBrains Mono', monospace", fontSize: 11 }}>
          No results — try refreshing or selecting a different filter
        </div>
      ) : (
        <div style={{ display: "flex", flexDirection: "column", gap: 1 }}>
          {articles.map((a, i) => (
            <a
              key={a.pmid}
              href={a.url}
              target="_blank"
              rel="noopener noreferrer"
              style={{
                display: "flex", gap: 14, alignItems: "flex-start",
                padding: "14px 16px",
                background: "rgba(255,255,255,0.018)",
                border: "1px solid rgba(255,255,255,0.06)",
                borderRadius: 4,
                textDecoration: "none",
                transition: "all 0.18s",
                animation: `fadeUp 0.3s ease ${i * 0.04}s both`,
                marginBottom: 6,
              }}
              onMouseEnter={e => { e.currentTarget.style.background = "rgba(255,255,255,0.04)"; e.currentTarget.style.borderColor = "rgba(255,255,255,0.12)"; }}
              onMouseLeave={e => { e.currentTarget.style.background = "rgba(255,255,255,0.018)"; e.currentTarget.style.borderColor = "rgba(255,255,255,0.06)"; }}
            >
              <span style={{
                fontFamily: "'JetBrains Mono', monospace", fontSize: 8,
                color: "rgba(52,211,153,0.6)", background: "rgba(52,211,153,0.07)",
                border: "1px solid rgba(52,211,153,0.15)", padding: "3px 7px",
                borderRadius: 2, flexShrink: 0, marginTop: 3, letterSpacing: "0.06em",
              }}>{a.pmid}</span>
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ fontSize: 13, color: "rgba(255,255,255,0.78)", lineHeight: 1.5, marginBottom: 4 }}>
                  {a.title.replace(/\.$/, "")}
                </div>
                <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: "rgba(255,255,255,0.28)", letterSpacing: "0.04em" }}>
                  {a.authors}{a.journal ? ` · ${a.journal}` : ""}{a.year ? ` · ${a.year}` : ""}
                </div>
              </div>
              <span style={{ color: "rgba(255,255,255,0.2)", fontSize: 14, flexShrink: 0, marginTop: 2 }}>↗</span>
            </a>
          ))}
        </div>
      )}
    </div>
  );
}

// ─── MAIN APP ────────────────────────────────────────────────────────────────
export default function App() {
  const [page, setPage] = useState("home");
  const [selected, setSelected] = useState(null);
  const [search, setSearch] = useState("");
  const [activeCategory, setActiveCategory] = useState("All");
  const [peptides, setPeptides] = useState(PLACEHOLDER_PEPTIDES);
  const [dbPeptides, setDbPeptides] = useState([]);
  const [loading, setLoading] = useState(true);
  const [categories, setCategories] = useState(STATIC_CATEGORIES);

  // Fetch peptides from database API
  useEffect(() => {
    async function loadPeptides() {
      try {
        const res = await fetch("/api/peptides");
        if (res.ok) {
          const data = await res.json();
          setDbPeptides(data);
          // Build dynamic categories from DB data
          const cats = ["All", ...new Set(data.map(p => p.category))].sort((a, b) => {
            if (a === "All") return -1;
            if (b === "All") return 1;
            return a.localeCompare(b);
          });
          setCategories(cats);
        }
      } catch (e) {
        console.warn("Could not load peptides from API, using static data");
      } finally {
        setLoading(false);
      }
    }
    loadPeptides();
  }, []);

  // Merge: use DB peptides for the database/home view, keep static for modal detail
  const allPeptides = dbPeptides.length > 0 ? dbPeptides : peptides;

  const filtered = allPeptides.filter(p => {
    const matchCat = activeCategory === "All" || p.category === activeCategory;
    const s = search.toLowerCase();
    const matchSearch = !search || (
      p.name.toLowerCase().includes(s) ||
      (p.fullName || "").toLowerCase().includes(s) ||
      (p.aliases || []).some(a => a.toLowerCase().includes(s)) ||
      (p.mechanism_of_action || "").toLowerCase().includes(s) ||
      (p.research_applications || p.uses || []).some(u => u.toLowerCase().includes(s)) ||
      p.category.toLowerCase().includes(s)
    );
    return matchCat && matchSearch;
  });

  const totalPeptides = allPeptides.length;
  const totalPubmedLinks = allPeptides.reduce((sum, p) => sum + (p.pubmed_links || p.citations || []).length, 0);

  return (
    <div style={{ fontFamily: "'Lato', sans-serif", background: "#08080f", minHeight: "100vh", color: "#e2ddd5" }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,700;1,400&family=Lato:wght@300;400&family=JetBrains+Mono:wght@300;400;500&display=swap');
        * { box-sizing: border-box; margin: 0; padding: 0; }
        ::-webkit-scrollbar { width: 4px; }
        ::-webkit-scrollbar-track { background: #08080f; }
        ::-webkit-scrollbar-thumb { background: #222230; border-radius: 2px; }
        @keyframes fadeIn { from { opacity: 0 } to { opacity: 1 } }
        @keyframes slideUp { from { transform: translateY(18px); opacity: 0 } to { transform: translateY(0); opacity: 1 } }
        @keyframes fadeUp { from { opacity: 0; transform: translateY(10px) } to { opacity: 1; transform: translateY(0) } }
        @keyframes pulse { 0%,100% { opacity: 0.4 } 50% { opacity: 0.7 } }
        @keyframes spin { from { transform: rotate(0deg) } to { transform: rotate(360deg) } }
        .pcard { transition: transform 0.25s ease, border-color 0.25s ease, background 0.25s ease; }
        .pcard:hover { transform: translateY(-2px); border-color: rgba(255,255,255,0.13) !important; background: rgba(255,255,255,0.035) !important; }
        .nav-item { fontFamily: 'JetBrains Mono', monospace; font-size: 11px; letter-spacing: 0.12em; text-transform: uppercase; cursor: pointer; color: rgba(255,255,255,0.35); transition: color 0.2s; padding: 6px 0; }
        .nav-item:hover { color: rgba(255,255,255,0.75); }
        .nav-item.active { color: #e2ddd5; }
      `}</style>

      {/* Disclaimer */}
      <div style={{
        background: "rgba(251,146,60,0.07)", borderBottom: "1px solid rgba(251,146,60,0.18)",
        padding: "7px 32px", textAlign: "center",
        fontFamily: "'JetBrains Mono', monospace", fontSize: 10,
        color: "rgba(251,146,60,0.75)", letterSpacing: "0.07em",
      }}>
        ⚠ FOR EDUCATIONAL & RESEARCH PURPOSES ONLY — NOT FOR HUMAN CONSUMPTION — NOT MEDICAL ADVICE
      </div>

      {/* Header */}
      <header style={{
        padding: "16px 40px", borderBottom: "1px solid rgba(255,255,255,0.055)",
        display: "flex", alignItems: "center", justifyContent: "space-between",
        position: "sticky", top: 0, background: "#08080f", zIndex: 100, gap: 16,
      }}>
        <div
          onClick={() => setPage("home")}
          style={{ display: "flex", alignItems: "baseline", gap: 8, cursor: "pointer" }}
        >
          <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: "rgba(255,255,255,0.25)", letterSpacing: "0.3em", textTransform: "uppercase" }}>PEPTIDE/</span>
          <span style={{ fontFamily: "'Playfair Display', serif", fontWeight: 700, fontSize: 20 }}>ATLAS</span>
        </div>
        <nav style={{ display: "flex", gap: 28, alignItems: "center" }}>
          {[["home", "Home"], ["database", "Database"], ["feed", "Live Feed"], ["about", "About"]].map(([p, label]) => (
            <span
              key={p}
              className={`nav-item ${page === p ? "active" : ""}`}
              style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 11, letterSpacing: "0.12em", textTransform: "uppercase", cursor: "pointer", color: page === p ? "#e2ddd5" : "rgba(255,255,255,0.35)", transition: "color 0.2s" }}
              onClick={() => { setPage(p); setSelected(null); }}
            >
              {label}
              {p === "feed" && (
                <span style={{
                  marginLeft: 6, display: "inline-block",
                  width: 5, height: 5, borderRadius: "50%",
                  background: "#34d399", boxShadow: "0 0 6px #34d399",
                  verticalAlign: "middle", marginBottom: 1,
                }} />
              )}
            </span>
          ))}
        </nav>
      </header>

      {/* HOME */}
      {page === "home" && (
        <main>
          <section style={{ padding: "72px 40px 52px", maxWidth: 980, margin: "0 auto" }}>
            <div style={{ animation: "fadeUp 0.5s ease 0.05s both" }}>
              <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: "rgba(255,255,255,0.28)", letterSpacing: "0.2em", textTransform: "uppercase", marginBottom: 22 }}>
                Peptide Research Database — 2026 Edition
              </div>
              <h1 style={{
                fontFamily: "'Playfair Display', serif", fontWeight: 400,
                fontSize: "clamp(38px, 5.5vw, 68px)", lineHeight: 1.1,
                letterSpacing: "-0.02em", marginBottom: 22,
              }}>
                The citation-backed<br />
                <em style={{ fontStyle: "italic", color: "rgba(255,255,255,0.42)" }}>peptide reference.</em>
              </h1>
              <p style={{ fontSize: 16, fontWeight: 300, color: "rgba(255,255,255,0.48)", lineHeight: 1.75, maxWidth: 520, marginBottom: 36 }}>
                Structured pharmacokinetic data, regulatory status, and peer-reviewed PubMed citations for {totalPeptides} research peptides. No affiliate links. No bro-science.
              </p>
              <div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}>
                <button onClick={() => setPage("database")} style={{
                  background: "#e2ddd5", color: "#08080f", border: "none",
                  padding: "11px 26px", fontFamily: "'JetBrains Mono', monospace",
                  fontSize: 11, letterSpacing: "0.1em", textTransform: "uppercase",
                  borderRadius: 3, cursor: "pointer", transition: "opacity 0.2s",
                }} onMouseEnter={e => e.target.style.opacity = "0.8"} onMouseLeave={e => e.target.style.opacity = "1"}>
                  Browse Database →
                </button>
                <button onClick={() => setPage("feed")} style={{
                  background: "rgba(52,211,153,0.1)", color: "#34d399",
                  border: "1px solid rgba(52,211,153,0.3)",
                  padding: "11px 26px", fontFamily: "'JetBrains Mono', monospace",
                  fontSize: 11, letterSpacing: "0.1em", textTransform: "uppercase",
                  borderRadius: 3, cursor: "pointer", transition: "all 0.2s",
                }}>
                  ● Live PubMed Feed
                </button>
              </div>
            </div>

            {/* Stats */}
            <div style={{
              display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(130px, 1fr))",
              gap: 1, marginTop: 56,
              background: "rgba(255,255,255,0.05)", borderRadius: 6, overflow: "hidden",
              animation: "fadeUp 0.5s ease 0.2s both",
            }}>
              {[
                { n: totalPeptides, label: "Peptides" },
                { n: totalPubmedLinks, label: "PubMed References" },
                { n: categories.length - 1, label: "Categories" },
              ].map((s, i) => (
                <div key={i} style={{ background: "#08080f", padding: "24px 22px", margin: 1 }}>
                  <div style={{ fontFamily: "'Playfair Display', serif", fontSize: 44, fontWeight: 700, lineHeight: 1, marginBottom: 4, color: i === 0 ? "#e2ddd5" : "rgba(255,255,255,0.65)" }}>{s.n}</div>
                  <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: "rgba(255,255,255,0.28)", letterSpacing: "0.12em", textTransform: "uppercase" }}>{s.label}</div>
                </div>
              ))}
            </div>
          </section>

          <section style={{ padding: "0 40px 72px", maxWidth: 980, margin: "0 auto" }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 24 }}>
              <h2 style={{ fontFamily: "'Playfair Display', serif", fontWeight: 400, fontSize: 24 }}>Featured entries</h2>
              <span onClick={() => setPage("database")} style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: "rgba(255,255,255,0.3)", cursor: "pointer", letterSpacing: "0.1em", textTransform: "uppercase" }}>View all →</span>
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(290px, 1fr))", gap: 10 }}>
              {allPeptides.slice(0, 6).map((p, i) => (
                <PeptideCard key={p.slug || p.id} peptide={p} onClick={() => setSelected(p)} delay={i * 0.06} />
              ))}
            </div>
          </section>
        </main>
      )}

      {/* DATABASE */}
      {page === "database" && (
        <main style={{ padding: "40px", maxWidth: 1120, margin: "0 auto" }}>
          <div style={{ marginBottom: 32, animation: "fadeUp 0.4s ease both" }}>
            <h2 style={{ fontFamily: "'Playfair Display', serif", fontWeight: 400, fontSize: 34, marginBottom: 6 }}>Research Database</h2>
            <p style={{ color: "rgba(255,255,255,0.35)", fontSize: 14, fontWeight: 300 }}>
              {filtered.length} of {totalPeptides} peptides · {totalPubmedLinks} total references
            </p>
          </div>
          <div style={{ display: "flex", gap: 12, flexWrap: "wrap", alignItems: "center", marginBottom: 16, animation: "fadeUp 0.4s ease 0.1s both" }}>
            <input
              placeholder="Search name, uses, category…"
              value={search}
              onChange={e => setSearch(e.target.value)}
              style={{
                background: "rgba(255,255,255,0.035)", border: "1px solid rgba(255,255,255,0.08)",
                color: "#e2ddd5", padding: "9px 15px", borderRadius: 4,
                fontFamily: "'JetBrains Mono', monospace", fontSize: 12, width: "100%",
                maxWidth: 360, outline: "none", letterSpacing: "0.04em", transition: "border-color 0.2s",
              }}
              onFocus={e => e.target.style.borderColor = "rgba(255,255,255,0.18)"}
              onBlur={e => e.target.style.borderColor = "rgba(255,255,255,0.08)"}
            />
          </div>
          <div style={{ display: "flex", gap: 7, flexWrap: "wrap", marginBottom: 28, animation: "fadeUp 0.4s ease 0.15s both" }}>
            {categories.map(c => (
              <button key={c}
                onClick={() => setActiveCategory(c)}
                style={{
                  border: `1px solid ${activeCategory === c ? "#34d399" : "rgba(255,255,255,0.18)"}`,
                  background: activeCategory === c ? "#34d399" : "rgba(255,255,255,0.05)",
                  color: activeCategory === c ? "#08080f" : "#e2ddd5",
                  padding: "7px 16px", borderRadius: 20,
                  fontFamily: "'JetBrains Mono', monospace", fontSize: 11,
                  letterSpacing: "0.08em", textTransform: "uppercase", cursor: "pointer", transition: "all 0.18s",
                  fontWeight: "500",
                }}
              >{c}</button>
            ))}
          </div>
          {filtered.length === 0 ? (
            <div style={{ padding: "72px 0", textAlign: "center", color: "rgba(255,255,255,0.2)", fontFamily: "'JetBrains Mono', monospace", fontSize: 11, letterSpacing: "0.1em" }}>NO RESULTS</div>
          ) : (
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))", gap: 10 }}>
              {filtered.map((p, i) => <PeptideCard key={p.slug || p.id} peptide={p} onClick={() => setSelected(p)} delay={i * 0.04} />)}
            </div>
          )}
        </main>
      )}

      {/* LIVE FEED */}
      {page === "feed" && (
        <main style={{ padding: "40px", maxWidth: 820, margin: "0 auto" }}>
          <div style={{ marginBottom: 32, animation: "fadeUp 0.4s ease both" }}>
            <h2 style={{ fontFamily: "'Playfair Display', serif", fontWeight: 400, fontSize: 34, marginBottom: 6 }}>Live Research Feed</h2>
            <p style={{ color: "rgba(255,255,255,0.35)", fontSize: 14, fontWeight: 300 }}>
              Real-time articles pulled directly from the PubMed E-utilities API — no caching, no editorializing.
            </p>
          </div>
          <div style={{ animation: "fadeUp 0.4s ease 0.1s both" }}>
            <LiveFeed />
          </div>
        </main>
      )}

      {/* ABOUT */}
      {page === "about" && (
        <main style={{ padding: "60px 40px", maxWidth: 660, margin: "0 auto" }}>
          <h2 style={{ fontFamily: "'Playfair Display', serif", fontWeight: 400, fontSize: 36, marginBottom: 30, animation: "fadeUp 0.4s ease both" }}>About Peptide Atlas</h2>
          <div style={{ color: "rgba(255,255,255,0.55)", fontSize: 15, lineHeight: 1.85, fontWeight: 300, animation: "fadeUp 0.4s ease 0.1s both" }}>
            <p style={{ marginBottom: 18 }}>Peptide Atlas is an independent research database providing structured, citation-backed pharmacokinetic data on research peptides. Every entry cites primary literature from PubMed.</p>
            <p style={{ marginBottom: 18 }}>Unlike vendor-driven peptide sites, we have no affiliate relationships, sell no products, and accept no advertising revenue. Our only goal is accuracy.</p>
            <p style={{ marginBottom: 32 }}>The Live Feed pulls directly from the NCBI PubMed E-utilities API in real time, surfacing the most recently indexed research on each peptide category.</p>
          </div>
          <div style={{
            background: "rgba(251,146,60,0.06)", border: "1px solid rgba(251,146,60,0.2)",
            borderRadius: 6, padding: "22px 26px", animation: "fadeUp 0.4s ease 0.2s both",
          }}>
            <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 9, letterSpacing: "0.15em", color: "rgba(251,146,60,0.65)", textTransform: "uppercase", marginBottom: 10 }}>Full Legal Disclaimer</div>
            <p style={{ fontSize: 12.5, color: "rgba(255,255,255,0.42)", lineHeight: 1.85, fontFamily: "'JetBrains Mono', monospace", fontWeight: 300 }}>
              All information on this website is provided for educational and research purposes only. The peptides discussed are intended strictly for laboratory research. They are not approved for human consumption, diagnosis, treatment, or prevention of disease unless explicitly noted as FDA-approved. Dosing figures are drawn from preclinical and clinical literature and do not constitute medical advice. Always consult a licensed medical professional.
            </p>
          </div>
        </main>
      )}

      {/* Footer */}
      <footer style={{
        borderTop: "1px solid rgba(255,255,255,0.055)", padding: "24px 40px",
        display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: 10,
      }}>
        <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: "rgba(255,255,255,0.18)", letterSpacing: "0.1em" }}>PEPTIDE/ATLAS © 2026</span>
        <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: "rgba(251,146,60,0.45)", letterSpacing: "0.08em" }}>FOR RESEARCH USE ONLY</span>
      </footer>

      {selected && <DetailModal peptide={selected} onClose={() => setSelected(null)} />}
    </div>
  );
}